### ISSUE TITLE
修改ws信令服务器之后，就不能访问本地视频了

### ISSUE THREAD

**Issue by weipt** [shushushv/webrtc-p2p#1]
修改ws://localhost:8080 为自己的ip之后就不能通信了，连本地视频摄像头也加载失败，为什么？

**Comment by shushushv** [comment]
1、"修改ws://localhost:8080 为自己的ip之后就不能通信了"，是指websocket连接失败？
2、“连本地视频摄像头也加载失败”，只有https或localhost环境下浏览器才允许调用摄像头，如 http://ip 会调用失败。

**Comment by weipt** [comment]
感谢回复，我也查到了，原因是浏览器只允许https和localhost接入。怎样搭建一个https呢

**Comment by shushushv** [comment]
node、nginx都可以，网上教程很多的~

**Comment by DarknessChaser** [comment]
新版chrome似乎localhost也要给https才行了，需要自签证书

**Comment by shushushv** [comment]
> 新版chrome建议本地主机也要给https才行了，需要自签证书

localhost 是没问题的呢，可以在控制台试试：navigator.mediaDevices.getUserMedia({video:true})

![image](https://user-images.githubusercontent.com/45039815/138273100-2f5d26c4-911a-474a-9c26-5e3d41281399.png)

**Comment by DarknessChaser** [comment]
> > 新版chrome建议本地主机也要给https才行了，需要自签证书
> 
> localhost 是没问题的呢，可以在控制台试试：navigator.mediaDevices.getUserMedia({video:true})
> 
> ![image](https://user-images.githubusercontent.com/45039815/138273100-2f5d26c4-911a-474a-9c26-5e3d41281399.png)

之前操作可能有误，打扰了。确实是可以的。
